blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('mypost_link/', views.postVew, name='posts')
]

custom_Users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('registrations/', views.RegistrationView.as_view()),
    path('login/', views.AuthLoginView.as_view(), name='home'),
    path('logout/', views.AuthLogoutView.as_view(), name='logout'),
    path('homepage/', views.UserListView.as_view(), name='post'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('disney.urls')),
    path('', include('parser_app.urls')),
    path('', include('custom_Users.urls')),
    path('', include('products.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/users/list_of_users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Вы успешно прошли регистрацию и авторизацию</h1>
<ol>
    {% for i in object_list %}
    <li>
        <h2>{{i.username}}</h2> - <em>{{i.email}}</em>
    </li>
    {% endfor %}
    <form action="{%  url 'users:logout' %}">
        {% csrf_token %}
        <button type="submit">Выйти из аккаунта</button>
    </form>
</ol>
</body>
</html>

templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Авторизация</h1>
<center>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Авторизация</button>
        <button><a href="/registrations/">У вас нет аккаунта?</a></button>
    </form>
</center>
</body>
</html>

templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Регистрация</h1>
<center>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Регистрация</button>
    </form>
</center>
</body>
</html>